name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 12 * * *' # Every day noon UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Looks like Github Actions leaks fds to child processes
    # https://github.com/actions/runner/issues/1188
    - run: ls -l /proc/self/fd

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Make "git describe" work

    # CI platform specific setup steps happen here
    - run: sudo apt-get install -qq fuse3 libssl-dev

    # Build & upload static binary
    - run: ./build-without-openssl.bash
    - uses: actions/upload-artifact@v2
      with:
        name: gocryptfs static binary
        path: gocryptfs

    # Actual test steps are in the Makefile
    - run: make ci
